# Generated by Django 4.1.3 on 2022-11-23 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, upload_to='media/images')),
                ('definition', models.TextField(blank=True, null=True, verbose_name="Ta'rif")),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Kordinata')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=6, verbose_name='Kordinata')),
                ('is_verified', models.BooleanField(default=False, verbose_name='HOLATI')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
