# Generated by Django 4.1.3 on 2022-11-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_alter_trees_latitude_alter_trees_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Kordinata'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=20, verbose_name='Kordinata'),
        ),
    ]
