# Generated by Django 4.1.3 on 2022-12-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_alter_trees_latitude_alter_trees_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='trees',
            name='qr_code',
            field=models.ImageField(default=0, upload_to='qr-code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trees',
            name='image',
            field=models.ImageField(blank=True, default='images/tree30.11.22.11:00.jpg', upload_to='images'),
        ),
    ]
