# Generated by Django 4.1.3 on 2022-12-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_trees_qr_code_alter_trees_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='qr_code',
            field=models.ImageField(blank=True, default='https://cdn.pixabay.com/photo/2014/12/22/00/07/tree-576847__480.png', upload_to='qr-code'),
        ),
    ]
